<?php

use App\Models\Category;
use App\Models\Note;
use Carbon\Carbon;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    private const SOURCE_METADATA = '{"source":"historical_backfill"}';

    /** Adds historical notes, conclusions, deletions and categories to the personal dashboard. */
    public function up(): void
    {
        DB::table('notes')->orderBy('id')->get()->each(function (object $note): void {
            $createdAt = $note->created_day
                ? Carbon::parse($note->created_day)->setTime(12, 0)
                : Carbon::parse($note->created_at);

            $this->insertWhenMissing(
                $note->user_name,
                'note_created',
                Note::class,
                $note->id,
                "Criou a nota \"{$note->title}\".",
                $createdAt,
            );

            if ($note->status === 'concluida') {
                $this->insertWhenMissing(
                    $note->user_name,
                    'note_completed',
                    Note::class,
                    $note->id,
                    "Concluiu a nota \"{$note->title}\".",
                    Carbon::parse($note->updated_at),
                );
            }

            if ($note->deleted_at) {
                $this->insertWhenMissing(
                    $note->user_name,
                    'note_deleted',
                    Note::class,
                    $note->id,
                    "Moveu a nota \"{$note->title}\" para a lixeira.",
                    Carbon::parse($note->deleted_at),
                );
            }
        });

        DB::table('categories')->orderBy('id')->get()->each(function (object $category): void {
            $this->insertWhenMissing(
                $category->user_name,
                'category_created',
                Category::class,
                $category->id,
                "Criou a categoria \"{$category->name}\".",
                Carbon::parse($category->created_at),
            );
        });
    }

    /** Removes only the historical records generated by this migration. */
    public function down(): void
    {
        DB::table('activities')->where('metadata', self::SOURCE_METADATA)->delete();
    }

    /** Inserts one historical event while preserving any activity already recorded in real time. */
    private function insertWhenMissing(
        string $userName,
        string $action,
        string $subjectType,
        int $subjectId,
        string $description,
        Carbon $createdAt,
    ): void {
        $exists = DB::table('activities')
            ->where('action', $action)
            ->where('subject_type', $subjectType)
            ->where('subject_id', $subjectId)
            ->exists();

        if ($exists) {
            return;
        }

        DB::table('activities')->insert([
            'user_name' => $userName,
            'action' => $action,
            'subject_type' => $subjectType,
            'subject_id' => $subjectId,
            'description' => $description,
            'metadata' => self::SOURCE_METADATA,
            'created_at' => $createdAt,
        ]);
    }
};
